// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using POSApi.Infrastructure.Data;

#nullable disable

namespace POSApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250409125811_Second_migration")]
    partial class Second_migration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("POSApi.Domain.Models.Kupac", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ADRESA")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MJESTO")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NAZIV")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SIFRA")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SIFRA")
                        .IsUnique();

                    b.ToTable("KUPAC");
                });

            modelBuilder.Entity("POSApi.Domain.Models.Proizvod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CIJENA")
                        .HasPrecision(20, 2)
                        .HasColumnType("decimal(20,2)");

                    b.Property<string>("JEDINICA_MJERE")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("NAZIV")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PROIZVODSlikaUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SIFRA")
                        .HasColumnType("int");

                    b.Property<int>("STANJE")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SIFRA")
                        .IsUnique();

                    b.ToTable("PROIZVOD");
                });

            modelBuilder.Entity("POSApi.Domain.Models.Stavke_racuna", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CIJENA")
                        .HasPrecision(20, 2)
                        .HasColumnType("decimal(20,2)");

                    b.Property<int>("KOLICINA")
                        .HasColumnType("int");

                    b.Property<decimal>("POPUST")
                        .HasPrecision(20, 2)
                        .HasColumnType("decimal(20,2)");

                    b.Property<int>("PROIZVODId")
                        .HasColumnType("int");

                    b.Property<int>("ZAGLAVLJE_RACUNAId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PROIZVODId");

                    b.HasIndex("ZAGLAVLJE_RACUNAId");

                    b.ToTable("STAVKE_RACUNA");
                });

            modelBuilder.Entity("POSApi.Domain.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CREATED_AT")
                        .HasColumnType("datetime2");

                    b.Property<string>("EMAIL")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NAZIV")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PASSWORD")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ROLE")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("EMAIL")
                        .IsUnique();

                    b.ToTable("USER");
                });

            modelBuilder.Entity("POSApi.Domain.Models.Zaglavlje_racuna", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BROJ")
                        .HasColumnType("int");

                    b.Property<DateTime>("DATUM")
                        .HasColumnType("datetime2");

                    b.Property<int>("KUPACId")
                        .HasColumnType("int");

                    b.Property<string>("NAPOMENA")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("BROJ")
                        .IsUnique();

                    b.HasIndex("KUPACId");

                    b.ToTable("ZAGLAVLJE_RACUNA");
                });

            modelBuilder.Entity("POSApi.Domain.Models.Stavke_racuna", b =>
                {
                    b.HasOne("POSApi.Domain.Models.Proizvod", "PROIZVOD")
                        .WithMany("STAVKE_RACUNA")
                        .HasForeignKey("PROIZVODId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("POSApi.Domain.Models.Zaglavlje_racuna", "ZAGLAVLJE_RACUNA")
                        .WithMany("STAVKE_RACUNA")
                        .HasForeignKey("ZAGLAVLJE_RACUNAId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PROIZVOD");

                    b.Navigation("ZAGLAVLJE_RACUNA");
                });

            modelBuilder.Entity("POSApi.Domain.Models.Zaglavlje_racuna", b =>
                {
                    b.HasOne("POSApi.Domain.Models.Kupac", "KUPAC")
                        .WithMany("ZAGLAVLJE_RACUNA")
                        .HasForeignKey("KUPACId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KUPAC");
                });

            modelBuilder.Entity("POSApi.Domain.Models.Kupac", b =>
                {
                    b.Navigation("ZAGLAVLJE_RACUNA");
                });

            modelBuilder.Entity("POSApi.Domain.Models.Proizvod", b =>
                {
                    b.Navigation("STAVKE_RACUNA");
                });

            modelBuilder.Entity("POSApi.Domain.Models.Zaglavlje_racuna", b =>
                {
                    b.Navigation("STAVKE_RACUNA");
                });
#pragma warning restore 612, 618
        }
    }
}
